SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='STRICT_TRANS_TABLES';

DROP FUNCTION IF EXISTS str_random;
DROP FUNCTION IF EXISTS str_random_character;
DROP FUNCTION IF EXISTS str_random_lipsum;
DROP FUNCTION IF EXISTS strip_tags;
DROP FUNCTION IF EXISTS str_count;
DROP FUNCTION IF EXISTS html_lipsum;


SET SQL_MODE=@OLD_SQL_MODE;
